### ISSUE TITLE
Unable to istall all the packages of the SDK

### ISSUE THREAD

**Issue by piste98** [OneIdentity/safeguard-sessions-plugin-sdk#2]
During the setting up of the environement with pipenv with my team, we've found some problem with the installation of the 37 python packages of the SDK. In particular if we use the python version 3.6 as suggested in the guide, all the packges' installation fails. We have tried also to use Python 3.9 and even if the situation became significatly better, we still be unable to complete the installation for 2 packages as you can see in the attached screenshots.
![Python3 6](https://user-images.githubusercontent.com/33320770/159436995-97751963-7de8-4652-8668-f112d14a55c8.png)
![Python3 6_1](https://user-images.githubusercontent.com/33320770/159436997-c6bbf504-1f0c-4d78-a855-6546a8b0a237.png)
![Python3 9](https://user-images.githubusercontent.com/33320770/159437001-73293ea8-6458-4458-a9f7-04c99b4c4b60.png)
![Python3 9_1](https://user-images.githubusercontent.com/33320770/159437002-f903ba5a-4bb3-4c2e-8d08-51b13ef7ab3f.png)

**Comment by andras-pinter** [comment]
Hi!

It seems like you are missing some package requirements from your system:
- libssl-dev
- libldap2-dev
- libsasl2-dev
- libffi-dev

You could install it via a package manager, for example on an Ubuntu
`apt install libssl-dev libldap2-dev libsasl2-dev libffi-dev`

Please let me know if it solved your issue.

**Comment by piste98** [comment]
Yes it works but after the installation of the packeges you have suggest I have changed the pipfile.lock at cffi packege in order to make it works 100%: form 1.12.4 to 1.15.0 and add the new sha256 to the list.

**Comment by andras-pinter** [comment]
Cool! I'm glad it solved your problem! :)
